version: '3.8'

services:
  plexamp-avr:
    build: .
    container_name: plexamp-avr
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/plexamp-avr.conf:/etc/plexamp-avr.conf:ro
      - ./data:/data
